public enum BlockType
{
    GrassUp,
    GrassLeft,
    GrassRight,
    GrassLeftRight,
    GrassUpLeft,
    GrassUpRight,
    GrassUpLeftRight,
    Bedrock,
    Breed,
    Eluvium,
    Ground,
    GroundUpLeft,
    GroundUpLeftRight,
    GroundUpRight,
    GumusHorizon,
    Iluvial,
    Podzol,
    Air = 255,
}
